### PR TITLE
Take missing "streetNameAndNumber" into account.

### PR DESCRIPTION
**Pull request by johnjohndoe**
+ Related: https://github.com/wo-ist-markt/wo-ist-markt.github.io/pull/323#discussion_r388172754.
+ This code change requires to define compatibility with ECMAScript 6.

### CODE REVIEW

**Review by mojoaxel — APPROVED** [review]
LGTM

**Comment by johnjohndoe** [comment]
Thanks. Feel free to merge.

**Comment by johnjohndoe** [comment]
@mojoaxel I manually re-triggered the build. No idea why Travis CI did not signal the status. Now the branch is mergeable.

**Comment by johnjohndoe** [comment]
Merci to @mojoaxel.

**Pull request merged**
