### PR TITLE
Add missing entry for Lübeck.

### PR DESCRIPTION
**Pull request by johnjohndoe**
+ Follow-up on pull request #299.

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@jbein You should be able to assign yourself and merge this pull request after you approved it.

**Comment by johnjohndoe** [comment]
@jbein Please refresh this page. The Merge button should be available now. I changed the settings.

**Comment by jbein** [comment]
@johnjohndoe Still not possible, because I'm not authorized.

image

**Comment by johnjohndoe** [comment]
@jbein This is correct. My mistake. I misinterpreted the [GitHub permission model](https://help.github.com/en/articles/repository-permission-levels-for-an-organization). Sadly, they do not have a fine tuned permission model. I am however happy to merge your approval. Thank you!

**Pull request merged**
