### PR TITLE
Add market data for Kiel

### PR DESCRIPTION
**Pull request by johan12345**

### CODE REVIEW

**Comment by johnjohndoe** [comment]
Rebased and merged [here](https://github.com/wo-ist-markt/wo-ist-markt.github.io/commit/0267946c4554d25459eed0366ab21814061902bf). Thank you and welcome to the map. Please promote the website in Kiel, see #38. Further, please tweet about the new entry (screenshot and link are helpful).

**Comment by johan12345** [comment]
@johnjohndoe Thanks! I [tweeted](https://twitter.com/johan_vf/status/759799718264311809) about it, but if [@stadt_kiel](https://twitter.com/stadt_kiel) does not react to it, I'll maybe also write an e-mail.

**Comment by johnjohndoe** [comment]
@johan12345 The URL for Kiel is no longer valid. You can see that if you run `npm test` locally. The closest I found is https://www.kiel-sailing-city.de/kieler-foerde-entdecken/shopping/flohmaerkte.html. Maybe, you find a better one. Please submit a pull request.

**Comment by johnjohndoe** [comment]
@johan12345 Did you also check if the market locations & times are still up-to-date? The last commit is a while ago..

**Comment by johan12345** [comment]
Yes, I checked that. It does not seem to have changed since then.

**Comment by johnjohndoe** [comment]
Nice. Thanks :+1:

**Comment by johnjohndoe** [comment]
In case you want to semi-automate stuff, have a look at the [preprocessing/](markt/wo-ist-markt.github.io/tree/master/preprocessing) script which I use for the data import of Berlin.

**Comment by johan12345** [comment]
In cases where
a) the number of markets is not that high (-> the frequency of changes is low) and
b) the city only provides the data as an HTML page, not in a nicely parseable format such as JSON,

wouldn't it be easier to just regularly monitor the page in `metadata.data_source.url` for changes with a notification when something is modified? Updating the data would be more manual work in that case, but one would not need to parse the HTML and always update the parser if the layout of the website is changed.

**Comment by johnjohndoe** [comment]
Very true. I would love to have such a service set up for the URLs in this project.

**Comment by johan12345** [comment]
For example something like https://github.com/thp/urlwatch looks quite straightforward

**Comment by johnjohndoe** [comment]
Thanks. By now I just use a client side solution like [Nock Nock](https://play.google.com/store/apps/details?id=com.afollestad.nocknock) for similar reasons. I will create an issue from your recommendation. The biggest blocker here is :bus: factor of :one: to maintain this project with all it's components.

**Pull request closed without merging**
