### PR TITLE
Update markets for Berlin (published 06.03.2018).

### PR DESCRIPTION
**Pull request by johnjohndoe**

### CODE REVIEW

**Comment by johnjohndoe** [comment]
I decided to keep them for reference because we are not using all the information which are contained in the original file. Also this gives the reviewer the chance to comprehend what the preprocessor extracted.

**Comment by dirkschumacher** [comment]
:shipit:

**Comment by johnjohndoe** [comment]
@dirkschumacher Now that you are a collaborator on the project you should have the permission to click the "Merge pull request" button yourself. Is this working for you?

**Comment by johnjohndoe** [comment]
Nice. :+1:

**Pull request merged**
