### PR TITLE
Update markets for Berlin (published 21.03.2024).

### PR DESCRIPTION
**Pull request by johnjohndoe**
+ Update data source URL as well.

### CODE REVIEW

**Comment by johnjohndoe** [comment]
:warning: There are multiple markets with wrong coordinates. I reported them to the data source owner to fix them.

**Comment by johnjohndoe** [comment]
:information_source: Some markets have been fixed but there is at least one off. Waiting for another update.

**Comment by johnjohndoe** [comment]
:warning: No idea what happens at the data holder but the data gets worse every time.

image

**Comment by johnjohndoe** [comment]
:warning: Still wrong coordinates. :facepalm:

**Comment by johnjohndoe** [comment]
:heavy_check_mark: Finally, the markets on the map have correct locations.

image

Just, it looks like there are less compared to former times. But that is a topic for later.

**Review by k-nut — APPROVED** [review]

**Pull request merged**
