### PR TITLE
Add Gemnasium badge.

### PR DESCRIPTION
**Pull request by johnjohndoe**

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@MorrisJobke Please feel free to merge the branch.

**Comment by MorrisJobke** [comment]
> @MorrisJobke Please feel free to merge the branch.

I'm not authorised 😉

**Comment by johnjohndoe** [comment]
I invited you to the webdev team now..

**Comment by MorrisJobke** [comment]
> I invited you to the webdev team now..

Haven't received any invitation.

**Comment by johnjohndoe** [comment]
@MorrisJobke Strange. GitHub shows the invitation as pending.

**Comment by MorrisJobke** [comment]
Found it - needed to go to https://github.com/wo-ist-markt to see the badge -.- (I also got no email or notification in the github notifications). After accepting this I also received the email -.-

**Comment by MorrisJobke** [comment]
@johnjohndoe Only assign me if the task is pending for me. Because I use it to manage my work. 😉

**Comment by johnjohndoe** [comment]
Super timing: https://gemnasium.com/blog/gemnasium-is-acquired-by-gitlab/ :-/

**Pull request merged**
