### PR TITLE
Fix #22: Put city dropdown into legend title.

### LINKED ISSUE #21: Select field "other city" does not work on mobile
I noticed that the **other city select box** added in #14 does not work when the website is visited on an Android phone (default browser). It does not respond when one touches it.
Also it should be larger on mobile to allow easier targeting.

Website on smartphone

### LINKED ISSUE #22: Make the city dropdown part of the legend title
Currently the city selection dropdown is a separate control at the bottom of the legend. I propose to use an appropriately styled dropdown as part of the legend title instead:

    Wo ist Markt in [Berlin   ▼]?

This has the following advantages:

* It reduces the size of the (already quite large) legend. That's especially important on mobile.
* It reduces the visual clutter by removing redundant information
* We could remove the "Andere Stadt?" label, freeing even more space.

### PR DESCRIPTION
**Pull request by torfsen**
This PR puts the city dropdown into the legend title (#22). I've also taken the opportunity and replaced the standard HTML `<select>` with the JQuery-based [select2](https://select2.github.io/), because the standard `<select>` is hard to style using CSS and hard to interact with using JS. In addition, select2 offers a search feature which might come in handy once we have data for more cities.

I've tested this on recent versions of Firefox and Google Chrome (both desktop and Android). It would be awesome if someone could test this on IE/Edge and Safari.

This PR also fixes #21 (Select field "other city" does not work on mobile).

### CODE REVIEW

**Comment by dirkschumacher** [comment]
Just tested it locally (using a local webserver) on Safari (Mac) and it appears not to be working. The Dropdown box is blank without any console error/warning. It is working on Chrome/Firefox.

bildschirmfoto 2016-03-26 um 09 58 22

Another remark:
I am currently using a very slow internet connection so for a couple of seconds the normal empty select box is shown before it is populated with the city names. Maybe you can add some kind of loading indicator?

**Comment by johnjohndoe** [comment]
@tursics Can you please test this on MacOS / Blackberry?

**Comment by torfsen** [comment]
@dirkschumacher: Thanks for the Safari test. Unfortunately I don't have any Mac hardware but I'll see if I can get Safari to run under wine. If you have time for more debugging that would be much appreciated.

A loading indicator is also a great idea, both for the initial page load and when switching cities. I'll add one.

**Comment by johnjohndoe** [comment]
> ... for the initial page load ...

Separate pull request please.

**Comment by torfsen** [comment]
>>     ... for the initial page load ...
>
> Separate pull request please.

@johnjohndoe Actually it's the other way round: Without #28 we only load data during page load, so there would only be one loading screen (until the list of cities and the current city data have been loaded). With #28 there would be a loading screen upon page load (same as before) and then whenever the city is changed (while the new city's data is being loaded).

However, I agree that a separate PR for the loading screen would be appropriate. I've filed #30 to track the issue. I've already got some code for it but I'd prefer to wait until we've sorted out this PR and #28.

That leaves the Safari issue to be fixed.

**Comment by torfsen** [comment]
I just installed Safari on my Ubuntu box via Wine. It crashes quite often so I couldn't figure out too much, but the problem seems to be that the GitHub API request fails. This also happens in the current master but there it's not that obvious because the dropdown is hidden until the data is loaded, so it just stays hidden on Safari.

So the problem is not caused by this PR, but nevertheless this PR makes the problem more obvious. I'm not sure how to proceed, since I cannot debug this any further with my less-than-stable Safari installation.

**Comment by tursics** [comment]
Like @dirkschumacher wrote: MacOS + Safari doesn't work, MacOS + Chrome/Firefox works. Blackberry works too. OK, only for published site (http:///), local site (file:///) results in CORS errors.

My Safari log a message:
Failed to load resource: Verbindung zum Server konnte nicht hergestellt werden. http://api.github.com/repos/wo-ist-markt/wo-ist-markt.github.io/contents/cities

**Comment by johnjohndoe** [comment]
@tursics You need to run the website via a local webserver. Just start it in the directory of the project.

```
$ python -m SimpleHTTPServer // Python 2
$ python3 -m http.server // Python 3
```

**Comment by tursics** [comment]
Thanks @johnjohndoe. The problem is the github API url. Don't use "//api.github.com", use "https://api.github.com" instead. This will work on Safari Mac.

(no, I can't create a PR yet)

**Comment by johnjohndoe** [comment]
I [changed the URL](https://github.com/wo-ist-markt/wo-ist-markt.github.io/commit/bcb8dd479b7db01a2209ebd89a48fa18e97e6a68) to [allow `https://`](https://github.com/wo-ist-markt/wo-ist-markt.github.io/issues/4).

**Comment by torfsen** [comment]
@johnjohndoe wrote:
> I changed the URL to allow https://.

Do we really need a protocol-agnostic URL here? HTTPS should also work if we force HTTPS for the GitHub API request, shouldn't it?

**Comment by johnjohndoe** [comment]
@torfsen I suggest you remove change the URL push to `master` - reload the page without caching (I used Tor browser). If it works - fine. If it does not work reset the last commit and force push `master` as if the commit was never there.

**Comment by torfsen** [comment]
I tried doing that just now, @johnjohndoe, but I noticed that event without that change HTTPS is still partially broken. I've reopened #4 and suggest that we fix that first before doing any more experiments on the Safari vs. GitHub API issue.

**Comment by torfsen** [comment]
Not that #4 is mostly resolved I did as @johnjohndoe suggested and changed the GitHub API URL to always use HTTPS. For all the browsers that I tested this still works, although I could test HTTPS only since http://wo-ist-markt.de redirects to https://wo-ist-markt.de (as it should :wink:).

@tursics, can you check again whether the city selection dropdown now appears and works using Safari on Mac?

**Comment by tursics** [comment]
\o/ now it works on Mac Safari.

**Comment by johnjohndoe** [comment]
If I understand right this is working now. @torfsen Can you please rebase the branch onto current _master_?

**Pull request merged**
