### PR TITLE
add Heilbronn's market data

### PR DESCRIPTION
**Pull request by Strubbl**

### CODE REVIEW

**Comment by johnjohndoe** [comment]
There are a couple of other markets announced on [the website](http://www.heilbronn-marketing.de/hn_content.asp?hmg=3xx51xx5xx0xx0&lang=01). Do you want to add them, too? Our project is open to add non-regular markets, too. You can use the [opening_hours evaluation tool](http://openingh.openstreetmap.de/evaluation_tool/) to check the opening hours formatting for such special dates.

**Comment by Strubbl** [comment]
The other events are not regular ones. All other events except the Pferdemarkt are fairs or festivals and not markets. 

In my opinion it only makes sense to add the Pferdemarkt, too. But only if it is okay to add markets which are only once a year.

**Comment by johnjohndoe** [comment]
That is fine for me. Go ahead.

**Comment by johnjohndoe** [comment]
@Strubbl I am happy to help if you need assistance. If you want to chat please join our Slack channel, see [`README.md`](https://github.com/wo-ist-markt/wo-ist-markt.github.io/#communication).

**Comment by johnjohndoe** [comment]
Hey @Strubbl, it would be great if you have time to add the Pferdemarkt and the other annual markets.

**Comment by johnjohndoe** [comment]
@Strubbl Are you going to finalize your pull request?

**Pull request closed without merging**
