### PR TITLE
Add flea markets in Hamburg

### PR DESCRIPTION
**Pull request by Roshanjossey**
Address #332

### CODE REVIEW

**Review by mojoaxel — APPROVED** [review]
LGTM

**Comment by johnjohndoe** [comment]
@Roshanjossey Is this still WIP?

**Comment by Roshanjossey** [comment]
@johnjohndoe, I wanted to add more from the data we have in hamburg.de.

But now, I have a better idea.

I'll create an issue detailing the changes that needs to be done to add further additions. If you could add a `good-first-issue` label, we could attract some new contributors to this project. So, this issue can act as an entry point for contributors to start with this project.

What do you think?

**Comment by johnjohndoe** [comment]
Sorry, I will not be able to access the repository for a while. Maybe,
somebody else from the contributors can take over now.

**Comment by johnjohndoe** [comment]
> I'll create an issue detailing the changes that needs to be done to add further additions. If you could add a `good-first-issue` label, we could attract some new contributors to this project. So, this issue can act as an entry point for contributors to start with this project.
> 
> What do you think?

Sounds good to me. There is already a [`For: Beginners`](https://github.com/wo-ist-markt/wo-ist-markt.github.io/labels/For%3A%20Beginners) label which we can use.

**Comment by Roshanjossey** [comment]
Cool. I'll do it then.

Also, I think `good first issue` good first issue label is better than `For: Beginners` For: Beginners because `good first issue` is a GitHub standard.

**Comment by johnjohndoe** [comment]
@Roshanjossey I am sorry that nobody took action here while I was away from keyboard. - I renamed the label as suggested. - How do you want to continue here?

**Comment by Roshanjossey** [comment]
@johnjohndoe, please merge this pull request. I've updated #332 to include other flea markets that can be included. Please add `good first issue` to that issue?

**Review by johnjohndoe — APPROVED** [review]
Thanks for the addition.

For a future pull request please consider adding a license and a date as mentioned in the [contribution guide](https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/master/CONTRIBUTING.md#market-data-contributions).

> It would also be great if you can specify the license under which the data is published as well as an update date. Both will be visible on the website so that users known how up-to-date the information is.

**Comment by johnjohndoe** [comment]
@Roshanjossey Please share the website with potential users, see #38.

**Comment by Roshanjossey** [comment]
@johnjohndoe, thank you. Sure. I'll share it in my circles.

**Comment by johnjohndoe** [comment]
@Roshanjossey Nice. As statistics show you reach the most people when you manage to convince the city to put a link to the Wo ist Markt? website onto their website, next to where they write about markets. A screenshot certainly helps.

**Comment by Roshanjossey** [comment]
@johnjohndoe, from this comment https://github.com/wo-ist-markt/wo-ist-markt.github.io/issues/38#issuecomment-284227997, I figured that they might not do it.

**Comment by johnjohndoe** [comment]
@Roshanjossey, sounds reasonable and I heard this before but I would try it anyway. People and opinions might have changed in 3 years. In Berlin I managed to put a link.

**Pull request merged**
