### PR TITLE
add package-lock.json

### PR DESCRIPTION
**Pull request by mojoaxel**
see https://github.com/npm/cli/blob/release-6.14.7/docs/content/configuring-npm/package-lock-json.md

> This file is intended to be committed into source repositories, and serves various purposes

### CODE REVIEW

**Review by Ryuno-Ki — APPROVED** [review]
Next step might be configuring renovatebot to open PRs with updated dependencies?

**Comment by Ryuno-Ki** [comment]
>  Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information. 

Error caused by

> npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.

**Review by Ryuno-Ki — APPROVED** [review]
For some reason, GitHub seem not to pick up my review outcomes :(

**Comment by johnjohndoe** [comment]
> For some reason, GitHub seem not to pick up my review outcomes :(

Do you want to try again or edit your comment?

**Review by Ryuno-Ki — APPROVED** [review]
:+1:

**Comment by Ryuno-Ki** [comment]
Nope:

getting-trolled

**Review by johnjohndoe — APPROVED** [review]
LGTM

**Pull request merged**
