### PR TITLE
Update data URLs

### PR DESCRIPTION
**Pull request by johnjohndoe**
- Schwerin seems to be responding again.
- Update outdated data source URLs.

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@k-nut I extracted these commits from #521 to fix the validation.

**Comment by johnjohndoe** [comment]
@k-nut I extracted these commits from #521 to fix the validation.

**Comment by johnjohndoe** [comment]
@mojoaxel Can you take care of this?

**Review by k-nut — APPROVED** [review]
LGTM 👍

**Pull request merged**
