### PR TITLE
Update markets for Berlin (published 02.12.2021).

### PR DESCRIPTION
**Pull request by johnjohndoe**

### CODE REVIEW

**Comment by johnjohndoe** [comment]
This PR will probably conflict with #431.

**Comment by johnjohndoe** [comment]
@rowbean Do you have time to review this change?

**Comment by johnjohndoe** [comment]
@ubergesundheit Do you have time to review this change?

**Comment by johnjohndoe** [comment]
@tursics Do you have time to review this change?

**Review by rowbean — APPROVED** [review]
valid json

**Pull request merged**
