### PR TITLE
Added market data for Mallorca

### PR DESCRIPTION
**Pull request by jbein**
So far, i believe everything was only about the German-speaking area? So I decided it is time to further internationalize this project. I've added a bunch of markets of the beautiful island Mallorca. If this commit finds attention, maybe it would be good to organize the json-files countrywise in the future?

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@jbein Great work. What an amount of markets! I hope you are using a script to retrieve and update the data. In case you haven't seen the [other repositories](https://github.com/wo-ist-markt) there are a few with regards to data processing for your inspiration. 

Regarding Mallorca - I am relaxed with adding it - we already added Basel. Isn't Mallorca half German anyway ^^?! I would also not change the project structure until there is a huge demand. For now there are these two exceptions - which is fine to me. - If anyone here has different opinion please speak up.

---

It would be great if you could also append a **date** to the `title` - so users know when the data has been updated. Please check _berlin.json_ for the format.

image

**Comment by jbein** [comment]
To be honest: I made a lot by hand. But for the future I will take a look into the other repositories. 

I've also added the date to the title.

**Comment by jbein** [comment]
I've used the English translation also in my other cities, so I'm fine with that.

**Comment by johnjohndoe** [comment]
Thank you. I squashed the two commits into one and merge them into `master`. I hope you can do some advertisement on Mallorca to make the website known to many people. See #38.

**Pull request merged**
