### PR TITLE
Nersingen

### PR DESCRIPTION
**Pull request by looniverse**
Wochenmarkt in 89278 Nersingen erfasst

### CODE REVIEW

**Comment by looniverse** [comment]
Gemeinde 89278 Nersingen hinzugefuegt

**Comment by johnjohndoe** [comment]
Hi @looniverse. Thank you for your contribution. I took a look at your branch. There are some points to be sorted out.

* We do **not** support **public holidays** yet, although the opening hours format does. You are using it here: `Fr 13:00-17:00; PH off`.
* Your branch is **not clean**. It contains commits from Ulm and Neu-Ulm. The cities have been added earlier. A branch should only contain changes for one context.

If you need help with the cleanup, please let me know. I am happy to help. In general, the [contribution guide](https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/master/CONTRIBUTING.md) provides basic information about branching and rebasing.

**Comment by johnjohndoe** [comment]
@looniverse Please let me know if I can help to sort out the issues.

**Comment by johnjohndoe** [comment]
@looniverse I will close this pull request since I could not reach you since weeks. Please re-open it as soon as you have time.

**Pull request closed without merging**
