### PR TITLE
Markets in Chemnitz

### PR DESCRIPTION
**Pull request by symptog**

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@symptog Thanks for the refactoring.

Please notice that the current version of our script does not support the full spectrum of opening hours as supported by _opening_hours.js_. In fact I can only see **six markets** of the 13 markets in your file. You should use the `opening_hours_unclassified` attribute for opening hours which cannot be automatically parsed. This is described in the [_data format_ section](https://github.com/wo-ist-markt/wo-ist-markt.github.io#data-format) of the _README.md_.

Please note you that you can preview the website if you start a local webserver in the root folder of the project such as `python3 -m http.server`. Then just visit `http://localhost:8000/#chemnitz` to see if markets are rendered.

Please add any corrections to the commit on this branch using `git commit --amend` and then update the branch and pull request via `git push --force origin market-data-chemnitz`.

**Comment by symptog** [comment]
There are only 6 places for markets in Chemnitz. At the current time all markets are rendered correctly. 
There are some other markets then "Wochenmarkt" at the same places, but there should be no time collisions.

**Comment by johnjohndoe** [comment]
We do not support different markets at the same place at different times. I suggest you take out future markets and leave currently valid times. Then please open an issue for this use case so we can discuss it.

**Comment by symptog** [comment]
done.

@johnjohndoe please have a look :)

**Comment by johnjohndoe** [comment]
@symptog `Wochenmarkt Rosenhof` and `Wochenmarkt Am Roten Turm / Am Wall` do not shop any opening hours information in their popup windows (since they only take place in autumn). A visitor of the website will not understand this.

**Comment by dirkschumacher** [comment]
:shipit:

**Comment by johnjohndoe** [comment]
@symptog Please have a look at #38.

**Pull request merged**
