### PR TITLE
Add market data for Kaiserslautern

### PR DESCRIPTION
**Pull request by marcusandre**
Hi,

I added market data for Kaiserslautern and hope everything fits well, since I followed the contribution guidelines. 

Greetings, Marcus

### CODE REVIEW

**Comment by johnjohndoe** [comment]
Is there no other markets in Kaiserslautern such as flea, book, bicycle markets? I found the [_Kulturmarkt_](https://www.kaiserslautern.de/tourismus_freizeit_kultur/kultur/kunst_museen/veranstaltungen/kulturmarkt/index.html.de) around Christmas - is this an annual event?

**Comment by marcusandre** [comment]
Hi @johnjohndoe. I will take a closer look, collect some more and re-commit my findings.

**Comment by johnjohndoe** [comment]
Feel free to **overwrite** your commit on **your** branch:

``` bash
git checkout cities/kaiserslautern
git add .
git commit --amend
git push --force origin cities/kaiserslautern
```

**Comment by marcusandre** [comment]
Hi @johnjohndoe,

> is this an annual event?

Yes. It is once a year around christmas. So, this is not a weekly market by definition.
There are no other weekly markets I know about, or I could find about in the interwebs.

**Comment by johnjohndoe** [comment]
Weekly is not a requirement.

**Comment by marcusandre** [comment]
> Weekly is not a requirement.

Okay, I understand. I guess this is what "opening_hours_unclassified" is for. I also set the "opening_hours" to `null`.

**Comment by johnjohndoe** [comment]
@marcusandre Thank you for adding Kaiserslautern. :green_apple: Welcome on Wo ist Markt?

In order to promote the project I would like to ask you for two tasks:
- [ ] Send a tweet with a screenshot and a link to the website
- [ ] Try to convince the city to link to our website, see #38

**Comment by marcusandre** [comment]
Sounds like a good idea to me. I'll do as soon as I can. :)

**Pull request merged**
