### PR TITLE
Feature/siegen

### PR DESCRIPTION
**Pull request by d-amend**
Hi, I added 3 markets for Siegen. 
David

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@d-amend Nice to see Siegen joining ... please also add Siegen to the `README.md` as mentioned in the [contribution guide](https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/master/CONTRIBUTING.md).

**Comment by d-amend** [comment]
@johnjohndoe sorry, I missed that one... I also added opening days despite the exact opening hours are unclear.

**Comment by d-amend** [comment]
Is there a notation for comments and holidays. Because there in the opening hours specification, there is one [Opening Hours Spec from OSM](https://wiki.openstreetmap.org/wiki/DE:Key:opening_hours/specification#explain:singular_day_holiday)
I tried `"opening_hours": "We, Sa "Vormittags"; PH off"` but the validator failed at the V of Vormittags.

**Comment by johnjohndoe** [comment]
@d-amend Please note that you can use the `opening_hours_unclassified` property as a fallback for all opening hours which cannot be parsed by the _opening_hours.js_ library.

**Comment by d-amend** [comment]
@johnjohndoe I used `opening_hours_unclassified` in the first place, but after reading the Opening Hours Spec for OSM I thought it would be better to have a machine readable field where holidays can be marked an so on. But if the parser didn't accept this format I am going to change it back and use the `opening_hours_unclassified` field

**Comment by johnjohndoe** [comment]
Public holidays only work when a country code is specified. At the moment we are not providing such information. That's why the library fails with the following error:

> Error: Country code missing which is needed to select the correct holidays (see README how to provide it)

Further, to my experience it is never guaranteed that the library can parse all the variants mentioned in the specification. The best is to try it and let Jenkins (`npm test`) approve it.

For now, I could only offer that we look at how to integrate country codes. This would be another issue/pull request. As a quick solution you might want to simplify your opening hours string or use the `opening_hours_unclassified` property.

**Comment by d-amend** [comment]
OK, so I use `opening_hours_unclassified` for now :)

**Comment by johnjohndoe** [comment]
It would be great if you could finally put all your changes in a **single commit**? The following commands should do it:

``` bash
$ git reset cd43f3 // The root commit of your branch
$ git add .
$ git commit -m "Add market data for Siegen."
$ git push -f origin feature/siegen
```

**Comment by d-amend** [comment]
done :D sorry for the clutter

**Comment by johnjohndoe** [comment]
No worries. Work in progress on a branch is perfectly fine.
Welcome to the map, Siegen! :+1:  It would be great if you could promote the page on Twitter as well as convince the city to link to the website. See  #38.

**Comment by johnjohndoe** [comment]
@d-amend Hello and happy new year. I noticed that the data source link to the website of Siegen does no longer work (HTTP 403). Can you please update the link and the market data if needed? Thank you.

**Pull request merged**
