### PR TITLE
Add Marl.

### PR DESCRIPTION
**Pull request by KGausM**
I just added my home city "Marl" to cities.json

### CODE REVIEW

**Comment by johnjohndoe** [comment]
Hi @KGausM, thanks for the addition. Please have a look at the contribution guide to complete addition.

https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/master/CONTRIBUTING.md

**Comment by KGausM** [comment]
Now I have created the "marl.json" file according to the "karlsruhe.json"
example file. But I don't know how or where to upload it to the project.

Regards
Klaus

Am Do., 27. Apr. 2023 um 12:00 Uhr schrieb ***@***.***>:

**Comment by johnjohndoe** [comment]
You can locally checkout the project via Git and then switch to your branch. If you are not familiar with this then just paste the content of the file here. I will take care of it later.

Alternatively, there is a browser-based editor by GitHub which your might want to try.

**Comment by KGausM** [comment]
I'm absolutely not familiar with Git. I just signed up at Githup to contribute to wo-ist-markt. 
I hope to learn and understand how to add cities, to be able to help out with more cities aroud my home town.

This is the content of my "marl.json" file:

{
    "crs": {
        "properties": {
            "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
        },
        "type": "name"
    },
    "features": [
        {
            "geometry": {
                "coordinates": [
                    7.083224,
                    51.659153
                ],
                "type": "Point"
            },
            "properties": {
                "location": "Marl Brassert",
                "opening_hours": "We, Sa 08:00-12:30",
                "title": "Wochenmarkt Brassert"
            },
            "type": "Feature"
        },
        {
            "geometry": {
                "coordinates": [
                    7.133100,
                    51.664054
                ],
                "type": "Point"
            },
            "properties": {
                "location": "Marl Hüls",
                "opening_hours": "Tu, Fr 08:00-12:30",
                "title": "Wochenmarkt Hüls"
            },
            "type": "Feature"
        },
        {
            "geometry": {
                "coordinates": [
                    7.093918,
                    51.645651
                ],
                "type": "Point"
            },
            "properties": {
                "location": "Stettiner Straße",
                "opening_hours": "Su[1] 11:00-18:00",
                "title": "Trödelmarkt tedox & Straßenverkehrsamt"
            },
            "type": "Feature"
        }
    ],
    "metadata": {
        "data_source": {
            "title": "Stadt Marl",
            "url": "https://www.marl.de/leben-wohnen/einkaufen/wochenmaerkte"
        }
    },
    "type": "FeatureCollection"
}

**Review by johnjohndoe — APPROVED** [review]
Your contribution looks great now! :+1: 

I added the `marl.json` file and updated the `README.md`. Please keep it up-to-date.

**Comment by johnjohndoe** [comment]
@KGausM, here are a few advertisement ideas - as you already know this website is **nothing without its users**.

- [ ] Tweet it out - don't forget a nice screenshot :bird: 
- [ ] Ask the city of Marl if they put a link and maybe a screenshot on their website. Some cities did that and one can clearly see the user increase in the stats! :cityscape: 
- [ ] Share the news with local newspapers :newspaper: 
- [ ] Print stickers and share them: the assets can be found in the [wo-ist-markt-media repository](https://github.com/wo-ist-markt/wo-ist-markt-media) :printer: 
- [ ] Become a living advertisement - print your own t-shirt - I did that! Same assets as above :shirt: 

Of course, if you come up with something ever cooler - please let me know!

**Pull request merged**
