### PR TITLE
Update markets for Berlin (published 14.02.2020).

### PR DESCRIPTION
**Pull request by johnjohndoe**
Valentines trees ...

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@InsulinJunkieDe @mojoaxel @rowbean Can you take the review on this pull request please?

**Comment by johnjohndoe** [comment]
>  valid geojson. I did not check if data is correct.

@mojoaxel I added you to the Web devs team. You should now be able to merge the pull request. Does it work for you?

**Comment by mojoaxel** [comment]
> @mojoaxel I added you to the Web devs team. You should now be able to merge the pull request. Does it work for you?

Yes I have access rights now, thanks! But this is not my PR, you should merge it yourself!

**Comment by johnjohndoe** [comment]
@mojoaxel The reviewer should merge it.

**Comment by johnjohndoe** [comment]
@mojoaxel Thank you.

**Pull request merged**
