### PR TITLE
Use subresource integrity with font-awesome cdn

### PR DESCRIPTION
**Pull request by dirkschumacher**
Same version, but with SRI. Also harmonized a few other link tags.

I got the SRI sha from here: https://www.bootstrapcdn.com/legacy/fontawesome/

Disclaimer, I used the Github web interface and have not tested it 🙃

### CODE REVIEW

**Comment by dirkschumacher** [comment]
Ok, looks good on netlify.

**Comment by johnjohndoe** [comment]
@dirkschumacher Where exactly can one find the SRI settings? Link/screenshot please.

**Comment by dirkschumacher** [comment]
I posted the link above? Is that what you mean? Just scroll down to v4.3.0

**Comment by johnjohndoe** [comment]
@dirkschumacher Ah! Thanks, I did not understand that I have to click on the black toggle button.

**Comment by johnjohndoe** [comment]
@dirkschumacher Note: This merge also makes your [patch-4](https://github.com/dirkschumacher/wo-ist-markt.github.io/tree/patch-4) branch redundant.

**Pull request merged**
