### PR TITLE
Updated Data for Essen

### PR DESCRIPTION
**Pull request by friesenkiwi**
Hi, I came across your project but was missing one market, so I added it (Borbeck, it was in the EVB PDF though).
One market was in there twice (Stoppenberg/Barbarossaplatz), probably because of the two masters (?)
Also, because title and location was always identical, I thought it might be more descriptive to switch the title to the township.
In the original PDF, there is the additional Information "keine Textilien" for Holsterhausen and "nur Lebensmittel im Frischebereich und Blumen" for Stadtmitte, it might be worth including, maybe in an extra field?

Diff is maybe a bit clumsy, because I edited via uMap and https://jsonformatter.curiousconcept.com/, is there any suggestion as for a better tool?

### CODE REVIEW

**Comment by dirkschumacher** [comment]
Since everything is in one line, it is impossible to review the changes. Would it be possible to reformat the  json that it is readable? It also looks like it was a one liner before.

**Comment by friesenkiwi** [comment]
Yes, it was an oneliner before. While looking for "json diff" I found http://json-diff.com/ and pasted the contents of https://raw.githubusercontent.com/wo-ist-markt/wo-ist-markt.github.io/master/cities/essen.json and https://raw.githubusercontent.com/friesenkiwi/wo-ist-markt.github.io/master/cities/essen.json
Unfortunately there is no option for a permalink, but I changed the file in the pull request to a formatted style. Will that help?

**Comment by dirkschumacher** [comment]
Great thanks. Looks good to me. :shipit:

**Comment by dirkschumacher** [comment]
I addition just a comment on the git commit message. 
It would be great use a more informative imperative sentence like: `Reformat Essen.json file` 
http://chris.beams.io/posts/git-commit/

**Comment by johnjohndoe** [comment]
@friesenkiwi Thank you for your adjustments.

Please note that we strongly discourage to commit on `master` as explained in the [contribution guide](https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/master/CONTRIBUTING.md). Pull requests should be on a separate branch which "grows" with `master`. I ask you politely to move your work to a separate branch and to create a new pull request since GitHub does not allow to update this one with a different branch name.

You might also want to change the order of work: Reformat the original file, then apply the market changes. This would produce a much more readable commits.

**Comment by schurig** [comment]
Hey @friesenkiwi, thanks for supporting us!

I wrote a script that generates the json file for Ruhrgebiet cities: https://github.com/CodeforRuhrgebiet/wo-ist-markt-google-spreadsheet-parser (I'll try to find a way to print out pretty json instead of a 1-liner)

You can find all raw data here: https://docs.google.com/spreadsheets/d/1UshjCoKV_ztjMIi5g2Va81pN2qQy7Go0LWd8hkufL6s/edit?usp=sharing

I've fixed both problems with #69. I guess it doesn't matter whether you merge this PR or mine @johnjohndoe.

**Comment by johnjohndoe** [comment]
@schurig Did you see that I wrote a preprocessor for Berlin as well? I used Javascript since the opening_hours.js library is available in Javascript.

**Comment by johnjohndoe** [comment]
@friesenkiwi I merged #69 - if this satisfies your issue please close this pull request.

**Comment by johnjohndoe** [comment]
@friesenkiwi Is this pull request done?

**Comment by friesenkiwi** [comment]
Sorry for the delay :-(
@schurig your hint came at the right time, thank you, I was about to do the formatting for all the cities...
It might be good to have the raw data google doc link documented somewhere on the website or the repo in case someone wants to contribute.

As for this PR, it is solved partly. Borbeck is in and the Stoppenberg/Barbarossaplatz duplicate is fixed. But Column I (Standort/Platz) is used for both location and title, which is a bit redundant. Using "Stadtteil" (Column H) as the title would make a bit more descriptive, in my opinion.

Also, in the original PDF, there is the additional Information "keine Textilien" for Holsterhausen and "nur Lebensmittel im Frischebereich und Blumen" for Stadtmitte, it might be worth including, maybe in an extra field?

Also sorry guys for not using an extra branch and being a bit negligent with the second Commit message :-/

**Comment by johnjohndoe** [comment]
@friesenkiwi Please sort out internally if you want to add an additional field. If so, feel free to create a proposal issue so we can discuss how this could work for all cities.

Pending question: Can this pull request be closed?

**Comment by friesenkiwi** [comment]
Yes, i'll close this PR, as the original issue has been solved.
What do you mean by "internally"? :-) Is this not internal enough for wo-ist-markt?

**Comment by johnjohndoe** [comment]
@friesenkiwi I referred to talking about the Google Doc content which is obviously not part of this repository. The Slack channel I created might be a good place for discussing things.

**Pull request closed without merging**
