### PR TITLE
Add Düsseldorf to the project

### PR DESCRIPTION
**Pull request by cknebel**
Hallo zusammen,
wir haben mal eine Datei für Düsseldorf erstellt. Müssen wir sonst noch was tun, damit das klappt - das Preview funktioniert schon, also wird das Format ok sein.
Danke
Christian

### CODE REVIEW

**Comment by johnjohndoe** [comment]
You can check the [preview rendering from GitHub](https://github.com/cknebel/wo-ist-markt.github.io/blob/patch-1/cities/d%C3%BCsseldorf.json) for the GeoJSON file.
To check the website preview you have to start a local webserver in the root folder of the project and the visit the path in the Browser such as here: `http://localhost:8000/#düsseldorf`

**Comment by cknebel** [comment]
Sorry that I forgot to add our links to the README.md. Now this is done. Data looks fine (online and on my localhost).

**Comment by dirkschumacher** [comment]
Could please you merge the two commits into one?

**Comment by johnjohndoe** [comment]
@cknebel 
Please rework your market data file. You have repetitive misspelled the `opening_hours` attribute; mind the underbar.
Please do not use German Umlauts in the Markdown links `[düsseldorf-wikipedia]` and `[düsseldorf-markets]` in the README.md.

**Comment by johnjohndoe** [comment]
Please note we [recently changed the infrastructure](https://github.com/wo-ist-markt/wo-ist-markt.github.io/commit/1b4f67f31d878b4f1d4fff40bca69fa71cfbc17d). You now have to add Düsseldorf to the city index in *cities/cities.json*.

Afterwards, please reduce your commits into one since later commits are "fixup" commits of the first commit. This can be done as follows:

```
git checkout patch-1
git rebase --interactive a395d
```
In the editor replace the `pick` with `fixup` for the latter commits. The last commit is at the bottom.
Then save and close the editor. Afterwards one commit should remain which contains all your changes.

Then, rebase your branch on top of the latest commit of the `master` branch. Here is how this works:

First, remove the commits you did on your `master` branch:

```
git checkout master
git reset --hard a395d
```

Then update your local `master` branch:

```
git pull wo-ist-markt master
git push origin master --force
```

Now rebase your branch on top of the latest commit of the `master` branch and update the corresponding GitHub branch as well as the pull request:

```
git rebase master patch-1
git push origin patch-1 --force
```

**Comment by cknebel** [comment]
Could you please delete this pull request? I cleaned up all the mess and started new (see pull request #96)...

**Pull request closed without merging**
