### PR TITLE
Clean-up unused deployment configuration and update documentation.

### PR DESCRIPTION
**Pull request by johnjohndoe**
+ Follow-up on: 9ccbd588fa273983cc97c97c240cfe133ae9682a.
+ The website hosting has been moved from a private server to [netlify.com](https://netlify.com). Former deployment (fabric, Python, `deploy.sh`) is no longer needed.
+ Let Travis CI automatically read the node version from the `.nvmrc` file.

# Related
- #348

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@k-nut anything I forgot to clean-up here?

**Comment by johnjohndoe** [comment]
Travis CI fails with:

> The command "rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION" failed and exited with 3 during .

@k-nut Do you remember why you added above `install` step in 3d304e15f38ce66f3fdfad300a40306b66c2c2f3? I am trying to use `.nvmrc` here as stated in the [Travis CI documentation](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions-using-nvmrc).

**Comment by k-nut** [comment]
I think I added this because we were using the travis python base configuration but wanted to install a specific node version. I think you can remove the whole `- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION` line.

**Review by k-nut — APPROVED** [review]
LGTM! ✨

**Pull request merged**
