### PR TITLE
Switch latitude and the longitude in Bruchköbel and Hanau

### LINKED ISSUE #122: Bruchköbel and Hanau on wrong positions
Both markets are in Somalia on the map. However, the coordinates are correct... Does I use a wrong format?

https://wo-ist-markt.de/#bruchk%C3%B6bel
https://wo-ist-markt.de/#hanau
https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/master/cities/bruchk%C3%B6bel.json?short_path=77c081c#L6
https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/master/cities/hanau.json?short_path=2cef9af#L6

Related to #119 and #121.

### PR DESCRIPTION
**Pull request by AltNico**
Fixes #122.

### CODE REVIEW

**Comment by johnjohndoe** [comment]
As a side note: please do not use the `master` branch to commit and send pull requests. Please always create a **separate branch** so you will be able to pull down changes made here without merge conflicts. More information in [CONTRIBUTION.md](https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/master/CONTRIBUTING.md).

**Comment by johnjohndoe** [comment]
@AltNico Please note that the changes might not be live immediately since we are currently migrating to a new server. The deployment is not yet automated. See #115.

**Comment by k-nut** [comment]
@AltNico @johnjohndoe just deployed. This is live now.

**Comment by AltNico** [comment]
@k-nut Thank you, Hanau is working now. However, when selecting 
Bruchköbel, the map does not get updated...

**Comment by johnjohndoe** [comment]
@AltNico I identified the problem, see #125. @k-nut Are you taking care of this?

**Pull request merged**
