### PR TITLE
improve data source URL validation

### PR DESCRIPTION
**Pull request by derhuerst**
see https://github.com/wo-ist-markt/wo-ist-markt.github.io/pull/359#issuecomment-813413395

### CODE REVIEW

**Review by johnjohndoe — APPROVED** [review]
Looks good to me. I quickly rebased your branch onto the latest commit of `master`. Besides: I had to upgrade my local `node` version in order to being able to use `URL`. We should probably specify the required node version somewhere.

**Comment by johnjohndoe** [comment]
Oh, I just realized now that you were targeting the `market-data-source-urls-validation` branch. Sorry.

**Comment by Ryuno-Ki** [comment]
> We should probably specify the required node version somewhere.

[package.json's engines field](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines) sounds like a sensible place.

**Comment by johnjohndoe** [comment]
@Ryuno-Ki Thanks. Addressed in c7e85721ed7a3a4e2b6d8ea427b426c025380075.

**Comment by derhuerst** [comment]
> Addressed in c7e85721ed7a3a4e2b6d8ea427b426c025380075.

FYI: While this makes the code run under the specified version of Node.js, it is certainly not the most debuggable or efficient way, because it will download a Node binary as an npm package.

**Comment by johnjohndoe** [comment]
@derhuerst Any suggestion? I am happy to change it.

**Comment by derhuerst** [comment]
As [@Ryuno-Ki pointed out, add `engines.node`](https://github.com/wo-ist-markt/wo-ist-markt.github.io/pull/360#issuecomment-815121438).

Unfortunately:

> Unless the user has set the `engine-strict` config flag, this field is advisory only and will only produce warnings when your package is installed as a dependency.

**Comment by Ryuno-Ki** [comment]
Alternatively, you could add a [`.nvmrc` file](https://github.com/nvm-sh/nvm/blob/master/README.md#nvmrc) (but that assumes the consumer would use the Node Version Manager).

**Comment by johnjohndoe** [comment]
I was using NVM at some point. `echo "node" > .nvmrc # to default to the latest version` sounds reasonable. Is _package.json_ also accepting such an alias or `stable` or such?

**Comment by derhuerst** [comment]
No, it needs a version range, but you can leave out the upper bound (e.g. `>= 12`) and assume that future Node.js versions will be backwards-compatible. This is not true all the time, at some point deprecated APIs get removed, but it's a reasonable compromise between maintainability and helpful error messages.

Having `stable` inside `engines.node` would defeat the point of it, because it's intended to express compatibility.

Also, note that `.npmrc` will only be respected if you actually use nvm to install Node.js. Otherwise, there won't be any warning. `engines.node` on the other hand is used by npm, which you will at least need to install dependencies, so you will always see the respective warning about incompatible versions.

**Pull request merged**
