### PR TITLE
Update markets for Berlin (published 30.08.2022).

### PR DESCRIPTION
**Pull request by johnjohndoe**
- Only write distinct features to output file. Duplicate entries are filtered out.

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@mojoaxel, please review if you have time.

**Comment by johnjohndoe** [comment]
@ubergesundheit, @rowbean, do you have time to review + merge this?

**Comment by k-nut** [comment]
@johnjohndoe looking at the `cities/berlin.json` file, it looks like every market is contained there four times now (exact same json structure, just four copies of it). Could you take a look at why this is happening?

**Comment by johnjohndoe** [comment]
@k-nut I just saw you comment now. Thanks. It look like the markets are published multiple times by the city. They only differentiate by an `href` and `id` property. I will reach out to the data owners to clarify this.

**Comment by johnjohndoe** [comment]
@k-nut Duplicate have been reduced but are not gone totally. I am still talking to the government.

**Comment by johnjohndoe** [comment]
@k-nut The preprocessed data now contains no duplicate features. Duplicate entries in the initial GeoJSON collection are filtered out by relying on all properties (`coordinates`, ...) except the `location` property which often contains different spelling of the same address.

**Review by k-nut — APPROVED** [review]
Nice, LGTM!

**Pull request merged**
