### PR TITLE
Issue #341 (WIP) Begin Moving to Rollup

### PR DESCRIPTION
**Pull request by jamessral**
This ends up being extra tricky as many of these modules are not meant to be packaged up in this way. They exist on npm, but only as a repository and often don't play well with common-js modules. 
There is also the issue of the css and the best way to bundle that here (or use cdn?).
Several of these modules also rely on globals.

I will open this as a draft for now, but I could use a little guidance here if it can be spared.

### CODE REVIEW

**Comment by mojoaxel** [comment]
@jamessral Maybe you want to merge https://github.com/jamessral/wo-ist-markt.github.io/pull/1

**Comment by mojoaxel** [comment]
@jamessral I think after merging https://github.com/jamessral/wo-ist-markt.github.io/pull/2, witch should fix the CI, you can remove the DRAFT status and we can discuss the changes. :rocket:

**Review by mojoaxel — APPROVED** [review]

**Comment by mojoaxel** [comment]
@johnjohndoe Are you ok with such a big change?

**Comment by johnjohndoe** [comment]
@mojoaxel As stated before I am not an expert in the topic JS package management / bundling. I noticed that [webpack](https://webpack.js.org/) is a thing. I haven't heard of [rollup](https://rollupjs.org) before. The only requirement I would set to myself is to use a library which is stable and somewhat well known. 

I had a look at the [preview generated by netlify](https://deploy-preview-346--wo-ist-markt.netlify.app/). At the moment it looks like the website is broken. Am I missing something here? Is the automatic deployment (modules) affected by the change?

With regards to the commits on branch: @jamessral Does it make sense to keep them in the history or would it clean up things to squash the intermediate steps before merging? I personally prefer a linear history (via _git rebase_) to benefit from the advantage of being able to _git bisect_ at any point in time. Also I strive after having each commit in history to represent a working state aka. building/running (if not marked explicitly in the commit message).

Please note that these are just my personal quality standards. This repository should incorporate the opinion of every active contributor.

**Comment by k-nut** [comment]
I think moving this to a bundler is a great idea 🚀

The netlify deploy currently does not work because netlify is set up so that it just takes the repo content and publishes it but this PR introduces a required build step.

I think that we should be able to get a nice preview again by setting the proper `command` and `publish` properties in a `netlify.toml` file. Maybe it actually makes sense to add one to this PR so that we can easily verify that the changes work as expected? See [the documentation here](https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file)

**Comment by jamessral** [comment]
I'll start working on that. Sorry, I haven't had a chance to check the netlify build yet, but I agree that it should be in working order before merging.

**Comment by jamessral** [comment]
It looks like it didn't re-run netlify, but the build does work correctly locally now, I'm not sure how to get it to rerun. I don't mind squashing commits at all, but I'm not sure how to do it now that there are a couple merge commits in the history. Merges and rebases tend to fight to the death. I will rebase in the future, however

**Comment by johnjohndoe** [comment]
Here is a simple way to "squash" the commits by creating a single new commit from all the changes:

``` bash
$ git checkout rollup-dependencies
$ git reset ebf72af0ab896feb9af0acf34d4ed2d9791ddeb0 // pointing to master
$ git add .
$ git commit
$ git push --force origin rollup-dependencies // updates this pull request
```

In the new commit message you can attribute @mojoaxel via `Co-authored-by: Alexander Wunschik <alex@wunschik.net>` as described [here](https://blog.k-nut.eu/extending-git-commits-with-trailers).

**Comment by johnjohndoe** [comment]
@jamessral Please rebase your branch onto the latest commit of `master`. The node-version has been raised to fix a build error. See #351.

**Comment by johnjohndoe** [comment]
@mojoaxel Can this pull request be closed in favor of #348 or do you want to keep it open for discussion/reference as long as the named replacement is not merged?

**Comment by johnjohndoe** [comment]
:x: I am closing this pull request now because #348 has been merged meanwhile. If anyone wants to pick up work here feel free to re-open it. Thanks to everyone who participated to drive the project forward.

**Pull request closed without merging**
