### PR TITLE
Remove font awesome

### PR DESCRIPTION
**Pull request by mojoaxel**
font-awesome is super big! We only need it for two icons:
- [x] the leaflet location button

  image

- [ ] the menu-button in the right upper order

  image

I replaced the icons with inline svg.

~~This should be merged after #348 !~~ :heavy_check_mark:

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@mojoaxel Looks like this is ready now. Can you rebase the branch please?

**Comment by mojoaxel** [comment]
I've rebased on master. But I'm not sure if the branch was ready...I need to have another look.
If you guys think it's ready feel free to merge it!

**Comment by johnjohndoe** [comment]
> I need to have another look.

Take your time.

**Comment by johnjohndoe** [comment]
@mojoaxel I rebased your branch, run `npm remove font-awesome` to update _package-lock.json_ and force pushed the branch. Please be welcome to take over again.

**Comment by mojoaxel** [comment]
@johnjohndoe sorry I'm completely overwhelmed by other stuff at the moment. But I'll be back when I can find the time...

**Comment by johnjohndoe** [comment]
@mojoaxel I can take over if that's okay to you. I have some spare time at the moment.

**Comment by johnjohndoe** [comment]
Yesterday, I took a look at the branch. I could find a similar icon for the menu button in the [Font Awesome](https://fontawesome.com) free collection. I thing however we could use some other icon such as an [info icon](https://fontawesome.com/v5.15/icons/info-circle?style=solid) or an [arrow icon](https://fontawesome.com/v5.15/icons/arrow-circle-down?style=solid) which points in a different direction depending on the menu state.

I did not yet manage to put the icon in place though. Help is welcome.

I edited the top post to clarify what is left to do.

**Comment by k-nut** [comment]
I don't see any blockers and think that this is ready to be merged :shipit:

**Comment by johnjohndoe** [comment]
@mojoaxel Finally, your work is merged :partying_face: Thank you!

**Pull request merged**
