### PR TITLE
Add Leipzig farmer's market

### PR DESCRIPTION
**Pull request by paesku**
I added Leipzig's farmer's market .

Sources are:
http://www.leipzig.de/freizeit-kultur-und-tourismus/einkaufen-und-ausgehen/maerkte/wochenmaerkte/
http://www.markt-finden.com/

Codestyle is hold and tests were run.

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@paesku There was already pull request #10 by @Drake81. I merged this now. You might wanna update the market data in the merged file. If so, please make sure to rebase your branch as described in the contribution guide.
Also, testing your branch the background map did not load for some reason.

**Comment by paesku** [comment]
@johnjohndoe Snap, I didn't see the PR from @Drake81. So we can close #11.

**Comment by johnjohndoe** [comment]
@paesku Did you check that there is no additional information in your file which you might wanna add? Just close the pull request yourself if you are finished.

**Comment by paesku** [comment]
@johnjohndoe yes, checked the json content. both of us had 15 farmer's market ;-)
I will close my PR.

**Comment by johnjohndoe** [comment]
You might wanna add:

> Daten von der Stadt Leipzig, CC BY 3.0 DE, aktualisiert am 19.03.2016

**Pull request closed without merging**
