### PR TITLE
Add today marker irrespective of opening hours

### LINKED ISSUE #246: Cannot click on `heute` if all markets that are open today are also open right now
Karlsruhe has 8 markets that are open on Saturday. If  the current time is 11:20 all markets are also open. In the header one can select `jetzt` and `alle` but not `heute`. Since this does not happen later on Saturdays I assume that the problem here only occurs if all markets that are open on the current day are also open at the current time. Obviously if one is able to select `jetzt` one should also be able to select `heute`.

### PR DESCRIPTION
**Pull request by stephanmax**
Changing the semantics of the today marker should do the trick.

Resolves #246.

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@k-nut This bugfix addresses the issue you reported in #246. Can you please take a look?

**Comment by k-nut** [comment]
It's rather difficult to test this until we resolve the GDPR stuff. I'll see if I can get around that within the next weeks.

**Comment by johnjohndoe** [comment]
@k-nut Locally, you can temporarily rename the files which I disabled in 5999642df3d3c784d08f093c9198c873e99c7822.

**Comment by k-nut** [comment]
@stephanmax sorry it took so long but now that the GDPR stuff is merged I'd be happy to look at this again. Are you comfortable with rebasing your changes on the lastest master?

**Comment by stephanmax** [comment]
Done, @k-nut.

**Comment by johnjohndoe** [comment]
I checked the markets in Karlsruhe and the radio boxes:

### Before: Today blocked
karlsruhe-today-blocked

### After: Today unblocked
karlsruhe-today-unblocked

@k-nut Looks good to me.

**Pull request merged**
