### PR TITLE
Fix opening hours/title at Wittenbergplatz Berlin

### PR DESCRIPTION
**Pull request by dirkschumacher**
This market is also opened on Thursday. Also changed the name as it said "Mehrere Einträge".

### CODE REVIEW

**Comment by johnjohndoe** [comment]
Please (also) send this to the source. Otherwise the change will be overwritten the next time we generate the data.

**Comment by dirkschumacher** [comment]
By source you mean berlin.de?

**Comment by johnjohndoe** [comment]
https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/master/cities/berlin.json?short_path=e9403ec#L2519

**Comment by dirkschumacher** [comment]
Ok I will send him an Email with the changes. I guess then we close the branch?

**Comment by dirkschumacher** [comment]
But do we know it is them and not us?

Why is the title "Mehrerer Einträge..."?

**Comment by johnjohndoe** [comment]
I use the [preprocessor script](https://github.com/wo-ist-markt/wo-ist-markt.github.io/tree/master/preprocessing) to automatically generate the GeoJSON file from the data published by the city.

**Comment by dirkschumacher** [comment]
Ah now I see. Maybe we need to alter the script so that it can handle multiple entries at the same place:
bildschirmfoto 2016-04-22 um 12 28 53

**Comment by johnjohndoe** [comment]
We had this [issue before](https://github.com/wo-ist-markt/wo-ist-markt.github.io/pull/56#issuecomment-210863956). We should definitely discuss how we are going to approach this case.

**Comment by dirkschumacher** [comment]
Yes, Let's maybe discuss on Monday then.

**Pull request closed without merging**
