### PR TITLE
feat(market-data): add market data for Essen

### PR DESCRIPTION
**Pull request by schurig**
Marktdaten für Essen

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@schurig Is `Fr 08:00-13:01` for `Bredeneyer-/Zeunerstraße` a typo?

**Comment by schurig** [comment]
@johnjohndoe yes, it was a typo. Thanks for letting me know! Fixed it.

Here is the data btw:
https://docs.google.com/spreadsheets/d/1UshjCoKV_ztjMIi5g2Va81pN2qQy7Go0LWd8hkufL6s/edit?usp=sharing

**Comment by johnjohndoe** [comment]
@schurig Please rebase your branch onto master.

**Comment by schurig** [comment]
@johnjohndoe done

**Comment by johnjohndoe** [comment]
Thanks! Merged. Welcome :rocket:

**Comment by johnjohndoe** [comment]
Please have a look at #38.

**Pull request merged**
