### PR TITLE
Enable Dependabot.

### PR DESCRIPTION
**Pull request by johnjohndoe**

### CODE REVIEW

**Comment by k-nut** [comment]
How does this relate to the setup that can be configured through the settings page as [described here](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/configuring-dependabot-security-updates)? When I check the [repo settings](https://github.com/wo-ist-markt/wo-ist-markt.github.io/settings/security_analysis), it seems like Dependeabot is already enabled for this repo.

**Comment by johnjohndoe** [comment]
Confusing. I started off from the [Dependency graph](https://github.com/wo-ist-markt/wo-ist-markt.github.io/network/updates) configuration page. Once I created the config file it contained a link to this [documentation page](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates) which is located under the "Auto-update dependencies" topic while the one you linked is located under "Fix vulnerable dependencies".

**Comment by k-nut** [comment]
Ah so the difference here is that in the UI one only enables security updates whereas your change also enables regular version updates?

**Comment by johnjohndoe** [comment]
No idea. I will have to read the docs to understand this. Or we just enable
it and see what happens.

**Review by k-nut — APPROVED** [review]
I guess it can't hurt to turn this on and to see what happens :shipit:

**Pull request merged**
