### PR TITLE
Create bonn.json

### PR DESCRIPTION
**Pull request by daimpad**
Die Bonner Marktdaten

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@daimpad Thanks for joining the project. I spotted a few things to improve:

* Please add Bonn to the alphabetic list of cities in the README.md.
* Please stick to the opening hours format ... use `08:00` instead of `8:00`.

**Comment by johnjohndoe** [comment]
Here is how you can update your `patch-1` branch on your local machine:

``` bash
$ git checkout patch-1
$ git rebase -i HEAD~3
```

Flag the latest two commits with the hash codes `b94df` and `c8faf` as `fixup`. Then save and leave the editor. This will merge the changes of these two commits into the first commit `1bd1c`. A single commit with as new has will be left on the branch `patch-1`.

Now reset and update your `master` branch to get the latest commits from this repository. This requires you have added this repository as a second remote named `wo-ist-markt` (or some other alias).

``` bash
$ git checkout master
$ git reset --hard d3752
$ git pull wo-ist-markt master
```

Now move your `patch-1` branch on top of `master`.

``` bash
$ git rebase master patch-1
```

Finally, push the branch to GitHub. This will update this pull request because GitHub recognizes the same branch name.

``` bash
$ git checkout patch -1
$ git push --force origin patch-1
```

**Comment by dirkschumacher** [comment]
I think something went wrong with the commit messages. Maybe our Chief Git Officer @johnjohndoe  can help?

**Comment by johnjohndoe** [comment]
@dirkschumacher: @daimpad and I were chatting about it on Monday. We will sort in out another day. We need some basic shell + Git setup first on Damian's machine. I assigned this pull request to me - just leave it as it is.

**Comment by johnjohndoe** [comment]
Nice! Welcome to the website :heart: 
Please have a look at #38.

**Pull request merged**
