### PR TITLE
Add select box to navigate to other cities

### PR DESCRIPTION
**Pull request by dirkschumacher**
Hola,

maybe a quick select box for navigation?

Dirk

### CODE REVIEW

**Comment by johnjohndoe** [comment]
Would be nice if we could omit hardcoding city names once more. Do you see chances to avoid this?
Please rebase onto master.

**Comment by dirkschumacher** [comment]
Well we would need to have a list of cities somewhere? I thought for a start I avoid making another GET request.

**Comment by johnjohndoe** [comment]
The original source would be the **file names** in the _cities/_ folder.

**Comment by dirkschumacher** [comment]
Does github.io return a file list when you make a get request for a folder? How else would know which files are in the cities folder?

**Comment by johnjohndoe** [comment]
Parsing from https://github.com/wo-ist-markt/wo-ist-markt.github.io/tree/master/cities feels dirty. GitHub's API might be more convenient ...

**Comment by johnjohndoe** [comment]
A saw that one [can read content via Javascript into GitHub pages](https://github.com/JakeWharton/butterknife/blob/gh-pages/index.html#L285) ...

**Comment by dirkschumacher** [comment]
:shipit:

**Pull request merged**
