### PR TITLE
city Fürth in Bavaria added

### PR DESCRIPTION
**Pull request by mojoaxel**

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@mojoaxel @ubergesundheit Please mind the [Market data format specification](https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/master/CONTRIBUTING.md#market-data-format-specification).

**Comment by ubergesundheit** [comment]
Since you didn't request changes, I don't get your comment. The file looks alright to me, so I'll merge this later..

**Comment by mojoaxel** [comment]
If you have anything I can improve please let me know! I did my best 😉

**Comment by johnjohndoe** [comment]
... from the contribution guide:

> It would also be great if you can specify the license under which the data is published as well as an update date. Both will be visible on the website so that users known how up-to-date the information is.

This would be great.

**Comment by mojoaxel** [comment]
> This would be great.

Done

**Comment by ubergesundheit** [comment]
@mojoaxel awesome! It would be even more awesome, if you could advertise the added data where you can (Check out #38).

**Comment by johnjohndoe** [comment]
@ubergesundheit I added Fürth to #38 so @mojoaxel can start promoting the website ^^

**Pull request merged**
