### PR TITLE
Add market data for Hamburg

### PR DESCRIPTION
**Pull request by alarmschaben**
Market data Hamburg

### CODE REVIEW

**Comment by alarmschaben** [comment]
Those two files are my vim undo files. They indeed do not belong here.

I shall try to squash those commits into one.

**Comment by alarmschaben** [comment]
That looks better. Fit for merge? :-)

**Comment by johnjohndoe** [comment]
Thanks for adding Hamburg. :fish: Great!
I rebased and merged your contribution here: 966f23dccdaf0f653f992922f4fc6d3f2255d8ac.
I also added the VIM undo files to the .gitignore list to avoid future hickups. See 16d63b76a68928f39a0f299a6cf968471c023449.

Now, it would be great to see a tweet with a screenshot and URL to advertise Hamburg being added.
Further, if you could convince the city to link our website on the official website - that would be awesome. Therefore, have a look at #38.

**Comment by alarmschaben** [comment]
That should be possible. I'll see what I can do later today.

**Pull request closed without merging**
