### PR TITLE
Update city data from google drive sheet

### PR DESCRIPTION
**Pull request by mrzmyr**
- Update title
- Remove "Markt in Vormholz" ([Twitter Ref](https://twitter.com/reclus23/status/752512724375072768))

### CODE REVIEW

**Comment by johnjohndoe** [comment]
Why do you revert the [title changes we made recently](https://github.com/wo-ist-markt/wo-ist-markt.github.io/commit/41d3da595d4290d368efd53990d8841a57c99702)? Please remove these changes from this commit.

You can update this commit as follows:

``` bash
$ git add CHANGED_FILES
$ git commit --amend
$ git push -f origin update-cities
```

**Comment by mrzmyr** [comment]
The titles weren't updated in the google spreadsheet I guess, thats why it got into it.

**Comment by johnjohndoe** [comment]
Better, just remove the unnecessary line space from the city files. See the diff.

**Comment by johnjohndoe** [comment]
Now you somehow put the changes into the merge request of @torfsen. Please do not modify commits which are already part of the `master` branch. You need to move your changes into a separate commit again.

**Comment by mrzmyr** [comment]
Woops, I think I messed it up a bit :grin:. I'm just gonna great a new PR.

**Pull request closed without merging**
