### PR TITLE
Update markets for Berlin (published 16.03.2020).

### PR DESCRIPTION
**Pull request by johnjohndoe**

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@rowbean I invited you to the `wo-ist-markt` GitHub organization so you can do a full review. Please note that you can preview the website when you click the `deploy/netlify -> Details` link in the `All checks have passed` section down here :arrow_down:

**Comment by rowbean** [comment]
> 
> 
> @rowbean I invited you to the `wo-ist-markt` GitHub organization so you can do a full review. Please note that you can preview the website when you click the `deploy/netlify -> Details` link in the `All checks have passed` section down here ⬇️
Thanks for the information.
Do I need to approve the changes again?

**Comment by johnjohndoe** [comment]
Can you assign yourself? Can you merge the pull request?

**Comment by rowbean** [comment]
It seems someone of "wo-ist-markt/web-devs" needs to review your pr.

**Comment by johnjohndoe** [comment]
@rowbean Please try now to assign yourself, review, approve and merge.

**Comment by rowbean** [comment]
I couldn't assign it to myself. Maybe someone else can review it.

**Comment by johnjohndoe** [comment]
@rowbean GitHub's configuration is a bit cumbersome. Sorry for that. Can you please try again?

**Comment by rowbean** [comment]
Sure, no problem. I can now assign myself, but not merge the pr.

**Comment by johnjohndoe** [comment]
@rowbean Is merge enabled now?

**Comment by rowbean** [comment]
@johnjohndoe No, but there is a green checkmark icon on "Changes approved" now.

**Comment by johnjohndoe** [comment]
@rowbean Sorry for the everlasting procedure. I changed the settings for your account once again. Can you try again to approve and merge, please?

**Comment by rowbean** [comment]
@johnjohndoe Don't worry. Merging is still blocked.

**Comment by johnjohndoe** [comment]
@rowbean I give up (for now). Thank you for your patience.

**Pull request merged**
