### PR TITLE
added market data for Hilden

### PR DESCRIPTION
**Pull request by aroskamp**

### CODE REVIEW

**Comment by torfsen** [comment]
Thanks for your contribution, @aroskamp! Could you please fix the following:

* Use a separate [feature branch](http://nvie.com/posts/a-successful-git-branching-model/) for your changes instead of `master`

See our [contributing guide](https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/master/CONTRIBUTING.md) for details and feel free to ask if you need help.

**Comment by k-nut** [comment]
@torfsen but @aroskamp did create a feature branch!? Their branch is called `market-data-hilden`. Or am I missing something here?

**Comment by aroskamp** [comment]
@torfsen @k-nut it is correct, i created a branch **market-data-hilden** on my side. I was working through the contribution guide. It is a good reference. Thank you for the guide.
Is it possible that i had some difficulties when i created the pull request???

**Comment by torfsen** [comment]
@aroskamp, @k-nut Ah, my bad, must have gotten target and source branch somehow mixed up :flushed:

In that case, welcome to the map, Hilden!

**Pull request merged**
