### PR TITLE
Updating Rostock market-data

### PR DESCRIPTION
**Pull request by Matthias84**
Update several markets at rostock

### CODE REVIEW

**Comment by johnjohndoe** [comment]
I ran the validator script on the change. There are some errors to fix:

```
ROSTOCK: Biogarten Rostock
Error: Attribute 'opening_hours_unclassified' cannot be undefined when 'opening_hours' is null.

ROSTOCK: Bio- und Erlebnisgärtnerei Rohde
Error: Th,Fr 10:00-16:00; Sa 10:00-13:00; nach Vereinbarung <--- (Bitte benutze die Schreibweise ""Nach Vereinbarung"" für "nach vereinbarung".)

ROSTOCK: Biestower Biobirne
Error: na <--- (Unexpected token: "n" This means that the syntax is not valid at that point or it is currently not supported.) nach <--- (Please omit "h" or use a colon instead: "12:00-14:00".)

ROSTOCK: Warnemünder Fischmarkt
Error: Sa-Su 08:00-18:00; Okt <--- (Bitte benutze die englische Abkürzung "Oct" für "okt".),Sa-Su 08:00-18:00; Okt-Mär <--- (Bitte benutze die englische Abkürzung "Mar" für "mär".)
```

Please `git commit --amend` them to this commit.

**Comment by Matthias84** [comment]
Ok, I guess this should fix the text string issues

**Comment by johnjohndoe** [comment]
Not yet. Please quote the `"` within the JSON string:

```
"opening_hours": "\"Nach Vereinbarung\"",
...
"opening_hours": "Th,Fr 10:00-16:00; Sa 10:00-13:00; \"Nach Vereinbarung\"",
...
"opening_hours": "\"Nach Vereinbarung\"",
```

**Comment by Matthias84** [comment]
@johnjohndoe  Thanks for the hint, I fixed the string encapsulation

While I agree, that this information are pretty unspecific, they are valid opening_times values. As there is no more specific information at the shop pages, there is nothing left I can do.

**Comment by johnjohndoe** [comment]
It would be great for visitors of the website when they can read when the market data was updated the last time. Here is how it is [done for Berlin](https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/master/cities/berlin.json?short_path=e9403ec#L2518):

updates

**Comment by Matthias84** [comment]
I added the line. It would be cool, if this could be auto-generated at the platform itself, by investigating the git history.

**Comment by johnjohndoe** [comment]
I would put the date manually because one might not have time to update the data here in a timely manner. Therefore, I would still put the date of the original publication.

**Comment by johnjohndoe** [comment]
Thx for the update :+1:

**Pull request merged**
