### PR TITLE
Notify Slack channel after Travis finishes

### LINKED ISSUE #139: Deployment notifications on Slack
It would be great if we could send an informative message to our [`#wo-ist-markt` Slack channel](https://openknowledgegermany.slack.com/archives/wo-ist-markt) every time the website is published. Since Travis CI is responsible for pushing stable changes to our server it should happen there. If possible it would be great to distinguish between general development and commits where actual market data is added or updated.

- [x] Setup of deployment notifications
- [ ] Custom market data notifications

### PR DESCRIPTION
**Pull request by k-nut**
Fixes #139 

Essentially this just adds one line which sets up travis so that it notifies the openknowledgegermany #wo-ist-markt channel whenever Travis finished. 

Since this contains an api key the values are encrypted like proposed in the [documentation](https://docs.travis-ci.com/user/notifications#Slack-notifications)

### CODE REVIEW

**Comment by johnjohndoe** [comment]
Hard to review or is there a way?

**Comment by k-nut** [comment]
You can check the channel on slack ;)

**Comment by johnjohndoe** [comment]
Just saw it. Okay. But can we list the commit summaries please?

**Comment by johnjohndoe** [comment]
Looks good - is there a test message I can see on Slack?

**Comment by k-nut** [comment]
For some reason there is not. I think this again is a thing that we could see and finetune only after merging to master.

**Comment by k-nut** [comment]
So should we merge this? 🚀

**Comment by johnjohndoe** [comment]
Merge here: 1198f46417f79a9d676c99f1ba0159be56d6daf8

**Pull request closed without merging**
