### PR TITLE
add Münster

### PR DESCRIPTION
**Pull request by ubergesundheit**
This will add all the markets of Münster except for two where we are lacking the local knowledge of the exact position.
We will create another pull request if the positions are known.

Btw nice project!

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@ubergesundheit Please first **rebase** your commit onto the current _HEAD_ of this repository. You are missing one commit for a clean merge. I suggest using a feature branch instead of working on the gh-pages branch.

**Comment by ubergesundheit** [comment]
I forked from the codeforkarlsruhe.. 

Rebase to wo-ist-markt/wo-ist-markt is done

**Comment by johnjohndoe** [comment]
Understood. But you did no rebase but a merge. Please do the following:

``` bash
$ git checkout gh-pages
$ git reset --hard HEAD~1 // This will delete the merge commit
$ git pull --rebase wo-ist-markt master // This will insert all missing commits before your commit
$ git branch muenster // This will create a new branch containing your commit
$ git reset --hard HEAD~1 // This will delete your commit on the gh-pages branch
$ git checkout muenster
$ git push origin muenster
```

Now you can create a new pull request based on the `muenster` branch. Alternatively I will just merge this branch without a pull request.
Please make sure not to work on the `gh-pages` branch since this will make collaboration more complicated. I will create a small contribution tutorial soon.

**Comment by ubergesundheit** [comment]
I would have been easier if it were clearly communicated from which repository external contributors should fork

**Comment by johnjohndoe** [comment]
True. Maybe I did not make this clear enough in the email.

**Pull request closed without merging**
