### PR TITLE
Update some dependencies

### PR DESCRIPTION
**Pull request by johnjohndoe**
- Here the following dependencies are updated:
  - moment.js
  - moment-range.js
  - select2.js + css
  - normalize.css

# Successfully tested on
- Ubuntu 18.04.4, Brave Version 1.11.104 Chromium: 84.0.4147.105 (Official Build) (64-bit), desktop & mobile devices modes

### CODE REVIEW

**Comment by mojoaxel** [comment]
It looks like `moment-range` and `select2` have not been dependencies until now!?

**Comment by johnjohndoe** [comment]
> It looks like `moment-range` and `select2` have not been dependencies until now!?

I am not a Javascript expert. Isn't it useful to have them mentioned in the dependencies block?

**Comment by Roshanjossey** [comment]
@johnjohndoe, if a package is in dependencies of  `package.json`, npm will download that package and put it in `node_modules` folder. The correct way to handle dependencies would be to use a package manager (npm or yarn) to manage them. 

In this project, these libraries are copied to `lib` directory. So, there is no need to add it in `package.json`.

The best way to move forward could be to not use `lib` directory and to use a package manager to handle dependencies for you. This will require some refactoring.

**Comment by Roshanjossey** [comment]
I also saw that two other libraries (colors and jshint) were outdated https://david-dm.org/wo-ist-markt/wo-ist-markt.github.io?type=dev

**Comment by johnjohndoe** [comment]
@Roshanjossey The setup probably is outdated. I am not sure though since JS is not my major field. To explain, we had the website running via GitHub pages at the beginning. Then we moved it to private server with automated deployment as explained in the README. For some reason we needed the dependencies being present in the `lib` folder. @k-nut might be able to explain this in details.

**Comment by mojoaxel** [comment]
I created an issue to discuss the handling of external libraries: #341

**Comment by johnjohndoe** [comment]
Replaced by #353.

**Pull request closed without merging**
