### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by johnjohndoe**
+ By running: `npm update`

### CODE REVIEW

**Comment by k-nut** [comment]
@johnjohndoe apparently travis-ci.org has stopped working now and one should use travis-ci.com instead. I have signed us up for the beta there (don't know why that was still required...) and migrated all WIM repos. Can you add an empty commit to see if this triggers a new run on travis-ci.com?

**Comment by johnjohndoe** [comment]
Oh. Just now? I can do it later. But I think you can trigger a manual build in the Travis CI user interface.

**Comment by johnjohndoe** [comment]
I am used to being able to trigger a manual build. Here is where you can do this:

travisci-more-options

trigger-build

It failed for me, though. Some authorization error.
travisci-requests-failure

Can you try this?

**Comment by k-nut** [comment]
I get the same message...

**Comment by k-nut** [comment]
Should we create a new ticket to migrate the checks to GitHub actions? I feel like Travis really is not the same anymore since they get bought, the experience certainly degraded recently.

**Comment by johnjohndoe** [comment]
Yes and no. Sometimes it is hard to understand the error. But I feel this was the case with them all the time. Lately, I was granted extra processing hours for another open source project which is very kind of them. 

In general there is nothing wrong about trying out alternatives. I haven't found the time to look into GitHub Actions, though.

**Comment by k-nut** [comment]
Ok, turns out [as per this Stackoverflow thread](https://stackoverflow.com/questions/41034694/travis-could-not-authorize-build-request/41078031) this was because I had not yet selected the free plan for the organisation. With that changed it now works again.

⚠️ I have also changed our branch protection rules for the `master` branch to required the new `Travis CI - Branch` check instead of the old travis ci check.

I think this is good to go. What do you think @johnjohndoe ?

**Review by k-nut — APPROVED** [review]

**Pull request merged**
