### PR TITLE
adding Munich markets based on City data

### PR DESCRIPTION
**Pull request by MarHai**

### CODE REVIEW

**Comment by johnjohndoe** [comment]
Great! Can you please **rebase** your commit onto current _HEAD_ of the _master_ branch? Further, it would be nice if you could **autoformat** the json file with an editor of your choice (e.g. Sublime Text - Indent JSON).

**Comment by johnjohndoe** [comment]
@MarHai I am sorry for the delay but I add a contributing guide now. I would like you to rewrite and rebase your branch. Feel free to ask for help if needed.
You have to create a separate branch for your changes and `reset --hard` your master to be able to pull changes I made on master here. Further please squash "local" changes such as formatting and fixed typo into earlier commits on your branch. I am totally fine when you force push commits while working on the branch.
Please note that GitHub does not allow to update this branch since you open a pull request base on your master. Therefore, you need to create a new pull request as soon as you created a new branch as mentioned earlier. Again, I am there to help if needed.

**Comment by johnjohndoe** [comment]
Here is what you can do:

### 1. Create a feature branch

``` bash
$ git checkout -b markets-munich 21e43ad
```

### 2. Cherry-pick commits with fixes onto the new branch

``` bash
$ git cherry-pick 32b98
$ git cherry-pick dd469
```

### 3. Squash later commits into initial commit

``` bash
$ git rebase -i 0f97f
```
- Flag the last two commits cherry-picked before as `squash`.
- Save this change and leave the editor. 
- Rewrite the commit message since the text of all three commits is combined.

### 4. Reset and update your master branch

``` bash
$ git checkout master
$ git reset --hard 0f97f
$ git pull wo-ist-markt master // or whatever you named the remote pointing here
```

### 5. Rebase your new branch onto master

``` bash
$ git rebase master markets-munich
```

**Comment by MarHai** [comment]
Followed your suggestions (see #16). I guess this one can be closed then.

**Pull request closed without merging**
