### PR TITLE
feat(Witten): add market data for Witten

### PR DESCRIPTION
**Pull request by schurig**
Market data for Witten

### CODE REVIEW

**Comment by schurig** [comment]
+ pretty json

**Comment by johnjohndoe** [comment]
Looks good. Please rebase your branch onto master.

**Comment by schurig** [comment]
@johnjohndoe done

**Comment by johnjohndoe** [comment]
Nice job. I am looking forward to reading a tweet with a screenshot and link. Also have a look at #38.

**Pull request merged**
