### PR TITLE
feat: add ludwigsburg

### PR DESCRIPTION
**Pull request by dersvenhesse**
Added Ludwigsburg as new city and unified minor wordings in readme.

### CODE REVIEW

**Review by johnjohndoe — CHANGES_REQUESTED** [review]
Hi @dersvenhesse. Thank you for the contribution. It looks great to me.

Two minor requests:
- Please add date to the data source to let people know when the market data has been updated the last time. Explained in the [contributing guide](https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/master/CONTRIBUTING.md#market-data-format-specification)
- Please split the fixes in the README and the changes for Ludwigsburg into two separate commits to have commits somewhat atomic.

If you need help or I should do the requested changes please let me know. Feel free to force-push your branch.

**Comment by dersvenhesse** [comment]
@johnjohndoe, done.

**Review by johnjohndoe — APPROVED** [review]
Thank you for the split.

**Comment by johnjohndoe** [comment]
@dersvenhesse Now that Ludwigsburg is on the map it is time for you to advertise them. There is a couple of ways to do this - and please let me know about your choice - but here is a few ideas:

- [ ] Tweet it out - don't forget a nice screenshot :bird: Or post it on Facebook
- [ ] Ask the city of Ludwigsburg if they put a link and maybe a screenshot on their website. Some cities did that and one can clearly see the user increase in the stats! :cityscape: 
- [ ] Share the news with local newspapers :newspaper: 
- [ ] Print stickers and share them: the assets can be found in the [wo-ist-markt-media repository](https://github.com/wo-ist-markt/wo-ist-markt-media) :printer: 
- [ ] Become a living advertisement - print your own t-shirt - I did that! Same assets as above :shirt: 

Also check issue #38.

**Pull request merged**
