### PR TITLE
Update markets for Berlin (published 19.09.2023).

### PR DESCRIPTION
**Pull request by johnjohndoe**
Finally, (after a few months :disappointed:) the Senat switched the GeoJSON data source back on so we can update the market data here.

# Description
+ Update data source URL.

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@k-nut Can you please check this PR?

**Comment by johnjohndoe** [comment]
@alexschnapper, @mojoaxel Do you have time to review this?

**Review by mojoaxel — APPROVED** [review]
Lgtm

**Comment by johnjohndoe** [comment]
Thanks. Feel free to merge it.

**Comment by johnjohndoe** [comment]
# CI failures

> Warning: köln: Error while accessing data source url: unable to verify the first certificate
> Warning: marl: Error while accessing data source url: connect ECONNREFUSED 185.41.57.95:443
> Warning: mallorca: HTTP response status of data source url was: 403
> Warning: potsdam: HTTP response status of data source url was: 301
>      --> New location: http://www.potsdam.de/de/kategorie/einkaufen-schenken
> Warning: rothenburgobdertauber: HTTP response status of data source url was: 404

**Pull request merged**
