### PR TITLE
do not update colors for now

### PR DESCRIPTION
**Pull request by mojoaxel**
see https://snyk.io/blog/open-source-npm-packages-colors-faker/
this replaces #450

### CODE REVIEW

**Comment by johnjohndoe** [comment]
Does this also prevent that the bad version is added as an transitive dependency of another package?

**Comment by mojoaxel** [comment]
> Does this also prevent that the bad version is added as an transitive dependency of another package?

Sadly not. But we will not get any more dependabot pull-requests for this package.

**Comment by johnjohndoe** [comment]
Dependabot supports ignoring version by sending a special comment.

**Comment by mojoaxel** [comment]
I think we should still freez the version (for now) so that developers who checkout the repository and run `npm install` run into this problem.

**Review by johnjohndoe — APPROVED** [review]

**Pull request merged**
