### PR TITLE
Always show all markets

### PR DESCRIPTION
**Pull request by torfsen**
Our current approach of only showing a single city's markets is starting to fail as more and more cities are added, see #116. This PR will provide the necessary changes to instead show all markets all the time. It is a work in progress and discussions on the best way to go forward are absolutely welcome!

My current plan for the design is as follows:
1. Keep data from separate cities in separate files. This eases maintenance, since each city's markets can be updated independently.
2. Use a build step that is executed after content has been updated and which aggregates all market data into a single file. The first commit in this PR provides this functionality, simply run `npm run build`. The plan is to run this via CI so nobody has to do it manually.
3. In the app, always show all markets. To keep things clean and fast we should probably use some kind of marker clustering so that individual markets are only shown once the zoom level is high enough.

The city navigation via the dropdown is also reaching its limits (see e.g. #40), but that's a topic for another PR.

### CODE REVIEW

**Comment by torfsen** [comment]
Some more work: The client now loads the data from the aggregated files (`build/markets.json` and `build/cities.json`) and displays the markets of all cities (instead of just the ones from the current city). 

The layer controls (now/today/all) are updated dynamically whenever the map view changes (move/zoom): The controls are enabled/disabled based on the markets in the current viewport instead of the markets of the currently selected city. Hence, if you select Karlsruhe but then move to Ulm (by dragging the map) then things will still work. If you move to an area where a more restrictive setting gets enabled (e.g. where there are "now" markets while your old view only had "today" markets) then the newly available control flashes for a short time to let the user know that they can restrict the display further.

If you change the view and the new view doesn't contain any markets of your current selection (e.g. you've selected "now" but then drag to an area where there are only "today" markets) then the setting is automatically "relaxed" so that at least some markets are shown (in the example, the setting would be relaxed from "now" to "today"). The user is alerted to this change visually (the new setting flashes for a short time).

Currently the logic basically just loops through all markets to detect which are visible. This is probably OK for the time but for the future we might want to implement faster lookups using a QuadTree, for example.

Marker clustering hasn't been implemented, either, yet.

I think the functionality introduced by these commits regarding the layer selection is quite useful and a reasonable extension of the old behavior to the new "show all markets" pragma. Other parts of the UI need a change, though: For example, the city dropdown should probably be made less obvious now and changed from being part of the heading to a simple "Jump to ..." command. The "data sources" display also needs some love, it should probably just display all sources now and could be moved to a separate page together with the other "about" stuff.

Currently the size of the aggregated download isn't that big (around 140K), but this will change if we add more cities and (as I would love to) more market types (e.g. flea markets). There isn't much room for minimizing GeoJSON, so the only other option I see is to serve markets for a given area dynamically. This would require some server side logic. @k-nut: What are our options on the new server? Can we, for example, run node?

**Comment by k-nut** [comment]
@torfsen yes, the server is under our control. We can do whatever we want ;) 

I already started a python project some time ago that lets users filter by date, maybe we could extend it for this. https://github.com/k-nut/markt-server

**Comment by johnjohndoe** [comment]
Here is a short review of the current draft:
- One of my first thoughts was that there might be a library which can help with the aggregation of GeoJSON. I guess you went for the manual solution because of the `metadata` block.
- I would love to see tests for the aggregations tasks.
- It would be helpful if you could put all sub task up as TODO list in your initial post.
- If you could later split your last commit into logical units (flashing, build integration, ..) it would be a bit easier to review.

**Comment by johnjohndoe** [comment]
I recently merged market data for Potsdam (which is close to Berlin), see #142. I noticed that Berlin also provides market data for Potsdam which overlaps with the data provided by Potsdam.
Therefore, once the changes of this issue are live we would have multiple markers for the same market. This should be fixed somewhen. Feel free to delay this issue and create a separate issue for it.

- [ ] De-duplicate identical markets

**Comment by johnjohndoe** [comment]
@torfsen Should we leave your pull request open or should we mark it as `Abandoned` and close it?

**Comment by johnjohndoe** [comment]
I am now closing this issue due to inactivity over the last years. If anyone is interested in the topic we can re-open it at any time. Thank you.

**Pull request closed without merging**
