### PR TITLE
Remove project authors and data source.

### PR DESCRIPTION
**Pull request by johnjohndoe**
+ The same information can be found in "info.html".
+ The expanded header does not take so much space
  anymore - specially on mobile devices.

wim

### CODE REVIEW

**Comment by torfsen** [comment]
Good idea! One thing that I would change while you're at it: better than

> Datenquelle: Stadt XYZ

would be

> Datenquelle for XYZ: Stadt XYZ

This might look redundant, but makes it clear that this is the data source for the *current* city, not for all cities. With the current version, people might misjudge the data source information as static without expecting it to change when they select a different city.

You're referring to `info.html`, but honestly the link to it in the map attribution is quite small. Perhaps we can replace the hamburger menu button and the info link by an info link in the toolbar that points to `info.html`? We could then list all data sources in a collapsed-by-default part of `info.html`.

**Comment by johnjohndoe** [comment]
@torfsen, thank you for your feedback. I rephrazed the data source statement to incorporate your suggestion. Here is a new screenshot of the current implementation draft:

wim-20180502

Regarding the additional comments I am happy to to discuss this in a separate issue/pull request. Issue #156 is somewhat related, too.

**Comment by johnjohndoe** [comment]
Pull request updated.

**Comment by johnjohndoe** [comment]
:+1: Thank you.

**Pull request merged**
